apiVersion: v2
name: leantime
description: A Helm chart for Kubernetes to deploy Leantime
type: application
version: 0.2.0
appVersion: "3.5.12"

dependencies:
- name: mariadb
  version: 24.1.1
  # Currently looking for alternatives as Bitnami has decided to stop publishing charts and container images
  # see https://github.com/bitnami/charts/issues/35164
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
